spring.application.name=rental-local
spring.profiles.active=dev


# Database connection
spring.datasource.url=jdbc:mysql://localhost:3306/rental_db
spring.datasource.username=root
spring.datasource.password=pranam@2151

# Driver
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect